PlantBay/Order/urls.py
from django.urls import path
from .views import (HomeView, add_to_cart, CheckoutView,
                     ItemDetailView, remove_from_cart, OrderSummaryView, 
                     remove_single_item_from_cart, Home_plant_View, PaymentView, AddCouponView,RequestRefundView,
                     Home_plant_supply_View,Home_plant_decor_View,SearchView,user_order,
                     )


app_name = 'Order'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('home_plant/', Home_plant_View.as_view(), name='home_plant'),
    path('search/', SearchView.as_view(), name='search'),
    path('home_plant_supply/', Home_plant_supply_View.as_view(), name='home_plant_supply'),
    path('home_plant_decor/', Home_plant_decor_View.as_view(), name='home_plant_decor'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order_summary/', OrderSummaryView.as_view(), name='order_summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add_to_cart/<slug>/', add_to_cart, name='add_to_cart'),   
    path('user_order/', user_order, name='user_order'),
    path('add_coupont/', AddCouponView.as_view(), name='add_coupon'),   
    path('remove_from_cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('remove_single_item_from_cart/<slug>/', remove_single_item_from_cart, name='remove_single_item_from_cart'),
    path('payment/<str:payment_option>/', PaymentView.as_view(), name='payment'),
    path('request_refund/', RequestRefundView.as_view(), name = 'request_refund')
]

PlantBay/PlantBay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('Order.urls', namespace='Order'))
]

if settings.DEBUG:
    # import debug_toolbar # type: ignore
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

PlantBay/Order/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.core.mail import send_mail
from PlantBay.settings import EMAIL_HOST_USER
import threading
from django.db.models.signals import post_save

# Email Thread
class EmailThread(threading.Thread):
    def __init__(self, subject, message, EMAIL_HOST_USER, recipient_list):
        self.subject = subject
        self.message = message
        self.EMAIL_HOST_USER = 'PlantBay <'+EMAIL_HOST_USER+'>'
        self.recipient_list = recipient_list
        threading.Thread.__init__(self)

    def run(self):
        send_mail(self.subject, self.message, EMAIL_HOST_USER, self.recipient_list) 

# Create your models here.
CATEGORY_CHOCIES = (
    ('P','Plants'),
    ('PS','Plan_Supplies'),
    ('GD','Garden_decorator')
)

LABEL_CHOCIES = (
    ('P','primary'),
    ('S','secondary'),
    ('D','danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

class Userprofile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(null=True, blank=True)
    category = models.CharField(choices=CATEGORY_CHOCIES, max_length=2)
    label = models.CharField(choices=LABEL_CHOCIES, max_length=1)
    description = models.TextField()
    slug = models.SlugField()
    image = models.ImageField(blank=True, null=True)


    def __str__(self):
        return self.title
    
    # ShortCut methos for getting url
    def get_absolute_url(self):
        return reverse("Order:product", kwargs={"slug": self.slug})
    
    def get_add_to_cart_url(self):
        return reverse("Order:add_to_cart", kwargs={"slug": self.slug})
    
    def get_remove_from_cart_url(self):
        return reverse("Order:remove_from_cart", kwargs={"slug": self.slug})
    
    
    
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True,null=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)


    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_item_price(self):
        return self.quantity * self.item.price
    
    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price
    
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()
    
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=50)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True
    )
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True
    )
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True
    )
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)


    '''
    Ordered life cycle
    1.item added to cart
    2.Adding billing Address
    3.Payment
    4.(preprocessing, processing, packing)Being delivered
    5.Received
    6.Refunds
    
    '''

    def __str__(self):
        return f"Order #{self.id}"
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total = total + order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user =models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order #{self.id}"
    

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code
    
class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"
    
def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = Userprofile.objects.create(user=instance)
        print("Inside Create")
        # Send Email
        subject = 'Account is Created' 
        message = 'Hi '+instance.username+','+' Thank you for choosing PlantBay'
        email =instance.email
        recipient_list = [email]
        # send_mail(subject, message, EMAIL_HOST_USER, recipient_list, fail_silently=True) 
        EmailThread(subject, message, EMAIL_HOST_USER, recipient_list).start()
        print("Message sended")
        # End of email send

post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

PlantBay/templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

PlantBay/templates/home.html
{% extends "base.html" %}

{% block content %}
<style>
  .card {
            width: 100%; /* Make the card's width 100% of its container */
            height: 100%; /* Ensure the card takes up the full height of its container */
        }

  .card-body {
      height: 200px; /* Set your desired height for the card body */
      display: flex;
      flex-direction: column;
      justify-content: space-between; /* Ensure the content is spaced evenly */
      align-items: center; /* Center the content horizontally */
      text-align: center; /* Center the text inside the card */
  }
  .card-img-top {
      height: 200px; /* Set your desired height */
      width: 100%; /* Make the width 100% of the card's width */
      object-fit: cover; /* Cover the entire area, maintaining aspect ratio */
  }
  .carousel-item img {
            height: 500px; /* Set your desired height */
            width: 100%; /* Make the width 100% of the container */
            object-fit: cover; /* Cover the entire area, maintaining aspect ratio */
  }
  .btn-icon {
            border: none;
            background-color: transparent;
            cursor: pointer;
            font-size: 24px; /* Adjust the size as needed */
            color: #333; /* Adjust the color as needed */
            transition: color 0.3s ease; /* Add a transition effect for hover */
        }

 .btn-icon:hover {
            color: #007BFF; /* Change color on hover */
        }
</style>
<main>
  <!-- SlideShow -->
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100"
          src="https://plantly.io/wp-content/uploads/2021/04/vadim-kaipov-8ZELrodSvTc-unsplash_1920x.jpg"
          alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100"
          src="https://plantly.io/wp-content/uploads/2021/04/vadim-kaipov-8ZELrodSvTc-unsplash_1920x.jpg"
          alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100"
          src="https://plantly.io/wp-content/uploads/2021/04/vadim-kaipov-8ZELrodSvTc-unsplash_1920x.jpg"
          alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <!-- EndofSlideShow -->

  <div class="container">
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% if request.path == '/' %}active{% endif %}">
            <a class="nav-link" href="/">All
              <!-- <span class="sr-only"></span> -->
            </a>
          </li>
          <li class="nav-item {% if request.path == '/home_plant/' %}active{% endif %}">
            <a class="nav-link" href="{% url 'Order:home_plant' %}">Plants</a>
          </li>
          <li class="nav-item {% if request.path == '/home_plant_supply/' %}active{% endif %}">
            <a class="nav-link" href="{% url 'Order:home_plant_supply' %}">Plan Supplies</a>
          </li>
          <li class="nav-item {% if request.path == '/home_plant_decor/' %}active{% endif %}">
            <a class="nav-link" href="{% url 'Order:home_plant_decor' %}">Garden decorator</a>
          </li>

        </ul>
        <!-- Links -->

        <form action="/search/" method="get" class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" name="q" class="search-input" placeholder="Search..." aria-label="Search">
          </div>
          <button type="submit" class="btn-icon">
            <!-- Replace with desired icon -->
            <i class="fas fa-search"></i>
        </button>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">
      {% if object_list %}

      <div class="row wow fadeIn">

        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card">

            <div class="view overlay">
              <!-- {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"> {% endcomment %} -->
              <!-- <img
                src="https://hips.hearstapps.com/hmg-prod/images/peace-lily-plant-in-a-bright-home-royalty-free-image-1715860400.jpg"
                class="card-img-top"> -->
              <img src="{{ item.image.url }}" class="card-img-top">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                </strong>
              </h4>

            </div>

          </div>

        </div>
        {% endfor %}
      </div>
      {% else %}
        <h3 class="text-center bold">No Item Found</h3>
      {% endif %}
    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

  </div>
</main>

{% endblock content %}

PlantBay/templates/navbar.html
{% load cart_template_tags %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">PlantBay</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
           <!-- <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/product">
            Product</a>
          </li> -->
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'Order:order_summary' %}" class="nav-link waves-effect">
                <!-- |cart_item_count -->
                 <!-- url 'core:order-summary'  -->
              <span class="badge red z-depth-1 mr-1"> {{ request.user | cart_item_count}} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'Order:user_order' %}">
              <span class="clearfix d-none d-sm-inline-block"> Your Order </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

PlantBay/templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'Order:add_coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

PlantBay/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<main>
  <div class="container">
    <div class="table-responsive">
        <h2>Order Summary</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Item title</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total Item Price</th>
                </tr>
            </thead>
            <tbody>
                {% for order_item in object.items.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order_item.item.title }}</td>
                    <td>{{ order_item.item.price }}</td>
                    <td>
                        <a href="{% url 'Order:remove_single_item_from_cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                        {{ order_item.quantity }}
                        <a href="{% url 'Order:add_to_cart' order_item.item.slug %}"><i class="fas fa-plus mr-2"></i></a>
                    </td>
                    <td>
                        {% if order_item.item.discount_price %}
                            ${{ order_item.get_total_discount_item_price }}
                            <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                        {% else %}
                            ${{ order_item.get_total_item_price }}
                        {% endif %}
                        <a style="color: red;" href="{% url 'Order:remove_from_cart' order_item.item.slug %}">
                            <i class="fas fa-trash float-right"></i>
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">Your Cart is Empty</td>
                    <td colspan="5">
                        <a class="btn btn-primary float-right" href="/">Continue Shopping</a>
                    </td>
                </tr>
                {% endfor %}
                {% if object.coupon %}
                <tr>
                    <td colspan="4">Coupon</td>
                    <td><b>-${{ object.coupon.amount }}</b></td>
                </tr>
                {% endif %}
                {% if object.get_total %}
                <tr>
                    <td colspan="4">Order Total</td>
                    <td><b>${{ object.get_total }}</b></td>
                </tr>
                <tr>
                    <td colspan="5">
                        <a class="btn btn-warning float-right ml-2" href="/checkout/">Proceed to Checkout</a>
                        <a class="btn btn-primary float-right" href="/">Continue Shopping</a>
                    </td>
                </tr>
                {% endif %}
            </tbody>
        </table>
      </div>
  </div>
</main>

{% endblock content %}

PlantBay/templates/product.html
{% extends "base.html" %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ object.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>
            <h4 class="lead font-weight-bold">{{ object.title }}</h4>
            <p class="">Description</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}